<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\AOT.props" />
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="Nerdbank.JsonRpc" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nerdbank.JsonRpc\Nerdbank.JsonRpc.csproj" />
  </ItemGroup>

</Project>