<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591;SA1600;SA1649;SA0001</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Contract\DemoContract.cs" Link="DemoContract.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Nerdbank.JsonRpc\Nerdbank.JsonRpc.csproj" />
    <ProjectReference Include="..\..\..\src\Nerdbank.JsonRpc.SourceGeneration\Nerdbank.JsonRpc.SourceGeneration.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Nerdbank.Streams" />
  </ItemGroup>
</Project>
