// Copyright (c) Andrew Arnott. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

#if NET
using System.Diagnostics.CodeAnalysis;
#endif

namespace Nerdbank.JsonRpc;

/// <summary>Identifies a proxy generated by an older version of the JSON-RPC source generator.</summary>
/// <remarks>Newly generated proxies use <see cref="JsonRpcProxyFactoryAttribute"/> to avoid constructor reflection.</remarks>
[Obsolete("This attribute is retained for compatibility with previously generated proxy assemblies.")]
[AttributeUsage(AttributeTargets.Interface, Inherited = false, AllowMultiple = false)]
public sealed class JsonRpcProxyImplementationAttribute : Attribute
{
	/// <summary>Initializes a new instance of the <see cref="JsonRpcProxyImplementationAttribute"/> class.</summary>
	/// <param name="proxyType">The generated proxy type.</param>
	public JsonRpcProxyImplementationAttribute(
#if NET
		[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)] Type proxyType)
#else
		Type proxyType)
#endif
	{
		this.ProxyType = proxyType;
	}

	/// <summary>Gets the generated proxy type.</summary>
#if NET
	[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)]
#endif
	public Type ProxyType { get; }
}
